// nextjs/app/dashboard/page.tsx
'use client';
import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { verifySession, logout } from '@/lib/auth';

export default function DashboardPage() {
  const router = useRouter();
  const [user, setUser] = useState('');
  const [marchaId, setMarchaId] = useState('');

  useEffect(() => {
    verifySession().then((s) => {
      if (!s) { router.replace('/login'); return; }
      setUser(s.user);
    });
  }, [router]);

  async function handleLogout() {
    await logout();
    router.push('/login');
  }

  function goToMarchaEdit() {
    if (!marchaId) return;
    router.push(`/dashboard/marcha/${marchaId}`);
  }

  return (
    <>
      <h1>WELCOME TO DASHBOARD {user}</h1>
      <div className="divider" />
      <div className="flex flex-wrap gap-3 items-end">
        <fieldset className="fieldset">
          <label className="label">ID de marcha a editar</label>
          <input
            className="input"
            type="number"
            min={1}
            value={marchaId}
            placeholder="Ej: 125"
            onChange={(e) => setMarchaId(e.target.value)}
            onKeyDown={(e) => e.key === 'Enter' && goToMarchaEdit()}
          />
        </fieldset>
        <button className="btn btn-neutral" onClick={goToMarchaEdit}>Ir a edición</button>
        <button className="btn btn-neutral" onClick={() => router.push('/dashboard/marcha/add')}>Nueva marcha</button>
        <button className="btn btn-neutral" onClick={() => router.push('/dashboard/autor/add')}>Nuevo autor</button>
        <button className="btn" onClick={handleLogout}>Logout</button>
      </div>
    </>
  );
}

// frontend/src/components/admin/Dashboard.vue
<script setup>
import { onMounted, ref } from 'vue';
import { useRouter } from 'vue-router';
import { getCurrentUser, logout } from '../../services/authService';

const router = useRouter();

const user = ref('');
const marchaId = ref('');

onMounted(() => {
  const session = getCurrentUser();
  user.value = session?.user || '';
});

async function goToLogout() {
  await logout();
  router.push('/login');
}

function goToMarchaEdit() {
  if (!marchaId.value) {
    return;
  }
  router.push({
    name: 'marchaEdit',
    params: { id: marchaId.value },
  });
}

function goToMarchaAdd() {
  router.push({ name: 'marchaAdd' });
}

function goToAutorAdd() {
  router.push({ name: 'autorAdd' });
}
</script>

<template>
  <h1>WELCOME TO DASHBOARD {{ user }}</h1>
  <div class="divider"></div>
  <div class="flex flex-wrap gap-3 items-end">
    <fieldset class="fieldset">
      <label class="label">ID de marcha a editar</label>
      <input
        class="input"
        type="number"
        min="1"
        v-model="marchaId"
        placeholder="Ej: 125"
        @keyup.enter="goToMarchaEdit()"
      />
    </fieldset>
    <button
      class="btn btn-neutral"
      @click="goToMarchaEdit()"
    >
      Ir a edición
    </button>
    <button
      class="btn btn-neutral"
      @click="goToMarchaAdd()"
    >
      Nueva marcha
    </button>
    <button
      class="btn btn-neutral"
      @click="goToAutorAdd()"
    >
      Nuevo autor
    </button>
    <button
      class="btn"
      @click="goToLogout()"
    >
      Logout
    </button>
  </div>
</template>
